### ISSUE TITLE
emit btf debug info for loading with libbpf-rs

### ISSUE THREAD

**Issue by dvc94ch** [aya-rs/bpf-linker#1]

**Comment by vlad9486** [comment]
Remove [this](https://github.com/alessandrod/bpf-linker/blob/a73b4833c30b960fb1b80928daab5e3aae4ab42c/src/llvm/mod.rs#L241) line, and use the linker with debug build.

But there is another problem: libbpf expect the structure has field `type`, but it is keyword in rust, and escaping does not help, debug info anyway containing `r#type` instead of `type`.

The simple solution is bithack of the bpf elf `sed -i 's/r#type/type\x0\x0/g' path/to/bpf.elf`.

**Comment by vlad9486** [comment]
Hello, @alessandrod thanks for the library, it is great. I think create a pr to remove few lines is overkill. Please, consider to remove [this](https://github.com/alessandrod/bpf-linker/blob/a73b4833c30b960fb1b80928daab5e3aae4ab42c/src/llvm/mod.rs#L241) line, or add an command line option.

**Comment by alessandrod** [comment]
I'll put the strip behind a command line flag, but I'm curious has anyone been getting segfaults generating BTF debug info? I know there's something that triggers a segfault in the BTF emitter in llvm, but haven't had time to look into it.

**Comment by vlad9486** [comment]
I have a bpf binary containing ring buffer, map, dozen of tracepoints and some non-trivial logic, I never saw a segfault during developing. But I saw some segfault when use release mode bpf binary, maybe it is how to reproduce the issue. Anyway it makes no sense to use release mode bpf with libbpf.

**Comment by vadorovsky** [comment]
Done in #182
